# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CarRecognition' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'AlamofireObjectMapper'
  pod 'VisionLab', git: 'https://github.com/cocoa-ai/VisionLab'

  target 'CarRecognitionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CarRecognitionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
